---
title: "Interactive report of the RBANS results"
author: "Lukáš 'hejtmy' Hejtmánek"
date: "`r Sys.Date()`"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    orientation: rows
---
```{r setup, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(plotly)
library(crosstalk)
library(knitr)
library(tidyverse)
knitr::opts_chunk$set(echo = FALSE)
#opts_knit$set(root.dir = "../")
```

```{r}
source("../functions/cdz-loading-pilot.R")
source("../functions/cdz-analysis.R")
source("../functions/cdz-helpers.R")
source("../functions/cdz-getters.R")
source("../functions/cdz-preprocess.R")
```

```{r loading}
df_results <- read.table("../run2-results-supermarket-sessions.csv", sep = ";",
                         header = TRUE)
df_demographics <- read.table("../demographics.csv", sep = ";", header = TRUE)
df_ids <- read.table("../information.csv", header = TRUE, sep = ";")
df_sessions <- read.table("../sessions.csv", header = TRUE, sep = ";")
df_rbans <- read.table("../rbans.csv", sep=";", header = TRUE) %>%
  add_session_to_rbans(df_demographics) %>%
  add_summaries_to_rbans()
```

```{r preprocessing}
df_rbans_long <- df_rbans %>%
    pivot_longer(-c(rbansid, trenink, diagnosis, first_training, session),
                 names_to = "subtest", values_to = "score")

df_rbans_long <- df_rbans_long %>%
  group_by(trenink, first_training, subtest) %>%
  summarise(group_avg = mean(score, na.rm = TRUE), .groups="drop") %>%
  right_join(df_rbans_long, by = c("trenink", "first_training", "subtest"))

df_rbans_long <- arrange(df_rbans_long, rbansid, session)
df_rbans_long <- mutate(df_rbans_long, fac_session = factor(session))

df_rbans_long <- df_rbans_long %>%
  group_by(session, subtest) %>%
  mutate(scaled_score = (score-mean(score, na.rm = TRUE))/sd(score, na.rm = TRUE)) %>%
  ungroup()
```

```{r}
shared_rbans <- SharedData$new(df_rbans_long)
```

Row {data-height=300}
---------------------------
### Visualisation of RBANS in different sessions
```{r}
selection_widget <- bscols(
  widths = 6,
  filter_select("subtest", "Subtest", shared_rbans, ~subtest, multiple = FALSE),
  filter_select("first_training", "Group", shared_rbans, ~first_training, multiple = FALSE)
)
selection_widget
```

Row {data-height=600}
---------------------------

### Visualisation of RBANS in different sessions

```{r}
plot_ly(shared_rbans, x = ~session, y = ~scaled_score) %>%
  add_trace(type = "box",  color = ~fac_session,
            hoverinfo = "y", showlegend = TRUE, boxmean = TRUE) %>%
  layout(showlegend = FALSE, autosize = TRUE, height = 500)
```

### Visualisation of RBANS in different sessions

```{r}
plot_ly(shared_rbans, x = ~session, y = ~scaled_score) %>%
  add_trace(type = "scatter", x=~fac_session, y = ~scaled_score,
            mode = "lines", split = ~rbansid, color = ~rbansid) %>%
  add_markers(x = ~jitter(as.numeric(session), amount = 0.02), y = ~scaled_score, color = ~rbansid) %>%
  layout(showlegend = FALSE, autosize = TRUE, height = 500)
```

```{r eval = FALSE}
df_rbans_long %>%
  filter(subtest == "iq_celek") %>%
  filter(first_training == "TP") %>%
  plot_ly(x= ~fac_session, y = ~scaled_score) %>%
    add_trace(type = "box",  color = ~fac_session,
            hoverinfo = "y", showlegend = TRUE, boxmean = TRUE) %>%
    add_trace(type = "scatter", y = ~scaled_score,
              mode = "lines+markers", split = ~rbansid) %>%
    layout(showlegend=FALSE)
````