---
author: "Lukáš 'hejtmy' Hejtmánek (hejtmy@gmail.com)"
date: "`r strftime(Sys.Date(), format = '%e. %m. %Y')`"
output: html_document
params:
  participant: NA
  data_dir: NA
title: "`r paste0('Report pro ', params$participant)`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(brainvr.supermarket)
library(tidyverse)
library(helprs)
source("../functions/cdz-loading-pilot.R")
source("../functions/cdz-analysis.R")
source("../functions/cdz-getters.R")
par <- params
df_sessions <- read.table("../sessions.csv", header = TRUE, sep = ";")
exps <- load_participant_supermarket(par$data_dir, par$participant)

results <- supermarket_results.participant(exps)

results <- results %>% 
  separate(timestamp, sep = "-", into = c("hour", "minute", "second", "day", "month", "year"), remove = FALSE) %>% 
  mutate(day = gsub("[0]([0-9])", "\\1", day),
         month = gsub("0([0-9])", "\\1", month)) %>%
  unite("date", c(day, month, year), sep = ".") %>%
  select(-c(hour, minute, second))

results <- results %>%
  left_join(filter(df_sessions, task == "supermarket", use),
            by = c("participant" = "id", "date" = "date")) %>%
  filter(!is.na(session)) %>%
  mutate(date.posix = as.POSIXct(date, format="%d.%m.%Y"))

results <- results %>%
  mutate(total_picked_items = n_correct_items + n_extra_items,
         correct_ratio = n_correct_items/n_items,
         extra_ratio = n_extra_items/n_items) %>%
  group_by(participant, session) %>%
  mutate(n_trials = n()) %>%
  ungroup()

CDZ_COLORS <- c("#63873a", "#f3f7e9", "#25aae1", "#81c6e2")
```

## Supermarket

V rámci studie jste absolvoval/a `r length(unique(results$timestamp))` sezení. První `r format(min(results$date.posix), "%d.%m.%Y")` a poslední `r format(max(results$date.posix), "%d.%m.%Y")`. 

V tomto grafu vidíte jaké maximální úrovně (počet předmětů na nákupním seznamu) jste v supermarketu v daný den dosáhl/a a jaká byla ten den vaše průměrná úspěšnost.

```{r}
results %>%
  group_by(date.posix) %>%
  summarise(max = max(n_items),
            correct = mean(correct_ratio)) %>%
  ungroup() %>%
  mutate(date.posix = as.Date(date.posix)) %>%
  ggplot(aes(date.posix, max)) +
    scale_x_date(date_labels = "%e.%B") +
    geom_line(aes(y = correct, color= "Úspěšnost"), size = 2) +
    geom_line(aes(y = max/11, color = "Dosažená úroveň"), size = 2) +
    scale_y_continuous(labels = function(x) x*11,
                       sec.axis = sec_axis(~.*100, name = "Úspěšnost %"),
                       limits=c(0,1), breaks = seq(0,1,1/11)) +
    geom_point(aes(y=correct), color = colors[3], size = 5) +
    geom_point(aes(y=max/11), color = colors[1], size = 5) +
    scale_colour_manual(values = colors[c(2,4)]) + 
    theme_bw() +
    labs(title = "Maximální dosažená úroveň a úspěšnost", 
         x = "", y = "Úroveň", colour = "") +
    theme(legend.position = "bottom")
```

```{r, results = 'asis'}
generate_trial_graph <- function(exp, i){
  trial <- get_trial_position(exp, i)
  cat('<div class="col-md-4 col-sm-12">')
    print(plot_supermarket_path(trial, background = TRUE, 
          color = CDZ_COLORS[3], size = 2))
  cat('</div>')
}

for(i in 1:length(exps)){
  exp <- exps[[i]]
  cat(as.character(htmltools::h3("Sezení ", i)))
  i_trials <- get_finished_trials_indices.supermarket(exp)
  for(i_trial in i_trials){
    generate_trial_graph(exp, i_trial)
  }
  cat(as.character(htmltools::div(class="row", out)))
}
```
